# Generated by Django 5.0.3 on 2024-03-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employes',
            new_name='Employe',
        ),
    ]
