# Generated by Django 5.0.3 on 2024-03-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_rename_employes_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='locatiojn',
            new_name='location',
        ),
    ]
