# Generated by Django 5.0.3 on 2024-03-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_rename_locatiojn_department_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='location',
            new_name='locatijon',
        ),
    ]
