# Generated by Django 5.0.3 on 2024-03-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_rename_location_department_locatijon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='locatijon',
            new_name='location',
        ),
    ]
